services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: knowledge_tracing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ..
      dockerfile: web_app/backend/Dockerfile
    environment:
      POSTGRES_DB: knowledge_tracing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      DKT_CKPT_DIR: /app/ckpts/dkt/ASSIST2009
      DKT_MAPPINGS_DIR: /app/datasets/ASSIST2009
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ..
      dockerfile: web_app/frontend/Dockerfile
    environment:
      VITE_API_URL: http://localhost:8000
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
